version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -v -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)
